server:
  port: 8002
spring:
  application:
    name: user
  cloud:
    consul:
        host: 127.0.0.1
        port: 8500
        discovery:
           register: false
#关闭login check
management.security.enabled: false
#开放所有页面节点  默认只开启了health、info两个节点
#management.endpoints.web.exposure.include: '*'
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true

#显示健康具体信息  默认不会显示详细信息
management.endpoint.health.show-details: always

management.endpoints:
  health.mapping.DOWN: OK
  health.mapping.OUT_OF_SERVICE : OK

feign.hystrix.enabled: false
#resilience4j:
#  circuitbreaker:
#    configs:
#      myDefault:
#        ringBufferSizeInClosedState: 10 # 熔断器关闭时的缓冲区大小
#        ringBufferSizeInHalfOpenState: 5 # 熔断器半开时的缓冲区大小
#        waitDurationInOpenState: 10 # 熔断器从打开到半开需要的时间
#        failureRateThreshold: 60 # 熔断器打开的失败阈值
#        eventConsumerBufferSize: 10 # 事件缓冲区大小
#        registerHealthIndicator: true # 健康监测
#        automaticTransitionFromOpenToHalfOpenEnabled: true # 是否自动从打开到半开
#    instances:
#      backendA:
#        baseConfig: myDefault
#        waitDurationInOpenState: 10
#        failureRateThreshold: 20

